{
 "title": "Kafka Cluster Health",
 "tags": [
  "Kafka",
  "Cluster",
  "Health"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Kafka Brokers Online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=~'kafka-[123]'}) or vector(0)"
    }
   ]
  },
  {
   "title": "Broker Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "up{job=~'kafka-[123]'}", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Prometheus Online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job='prometheus'}) or vector(0)"
    }
   ]
  },
  {
   "title": "Prometheus TSDB Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_symbol_table_size_bytes or vector(0)",
     "legendFormat": "TSDB Size"
    }
   ]
  }
 ]
}